---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cc-local-csi
provisioner: cc.local.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
